./shapes_test.go:38:12: cannot use rectangle (type Rectangle) as type Shape in argument to checkArea: 	Rectangle does not implement Shape (missing Perimeter method) ./shapes_test.go:53:12: cannot use circle (type Circle) as type Shape in argument to checkArea: 	Circle does not implement Shape (missing Perimeter method)