--- FAIL: TestUpdate (0.00s)     --- FAIL: TestUpdate/new_word (0.00s)         dictionary_test.go:85: got error %!q(<nil>) want "cannot update word because it does not exist" given, "test" FAIL exit status 1 FAIL	github.com/nadgerz/go/learn_go_with_tests/maps	0.009s